name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.X
    - name: Restore dependencies
      run: dotnet restore "./PlcSimAdvancedInterface"
    - name: Build
      run: dotnet build "./PlcSimAdvancedInterface" --no-restore
    - name: Test
      run: dotnet test "./PlcSimAdvancedInterface" --no-build --verbosity normal
    - name: Publish
      run: dotnet publish "./PlcSimAdvancedInterface" -c Release -o PlcSimAdvancedInterface
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: plc-sim-advanced-interface
        path: "./PlcSimAdvancedInterface"
